# Generated by Django 4.1.9 on 2023-06-05 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ElevatorSystem",
            fields=[
                ("id", models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("floors", models.IntegerField(default=0)),
                ("num_elevators", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ElevatorRequest",
            fields=[
                ("id", models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ("called_at", models.IntegerField(default=0)),
                ("destination_floor", models.IntegerField(default=0)),
                (
                    "direction",
                    models.CharField(choices=[("1", "1"), ("0", "0"), ("-1", "-1")], default="1", max_length=2),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "elevator_system",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="elevators.elevatorsystem"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Elevator",
            fields=[
                ("id", models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ("current_floor", models.IntegerField(default=0)),
                (
                    "direction",
                    models.CharField(choices=[("1", "1"), ("0", "0"), ("-1", "-1")], default="0", max_length=2),
                ),
                ("door_open", models.BooleanField(default=False)),
                ("oprational", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "elevator_system",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="elevators.elevatorsystem"),
                ),
            ],
        ),
    ]
