# Generated by Django 4.1.9 on 2023-06-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elevators", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="elevator",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="elevatorrequest",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="elevatorsystem",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
