# Generated by Django 4.1.9 on 2023-06-06 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("elevators", "0003_rename_oprational_elevator_operational"),
    ]

    operations = [
        migrations.AddField(
            model_name="elevatorrequest",
            name="elevator",
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to="elevators.elevator"),
            preserve_default=False,
        ),
    ]
