# Generated by Django 4.1.9 on 2023-06-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elevators", "0004_elevatorrequest_elevator"),
    ]

    operations = [
        migrations.AddField(
            model_name="elevatorrequest",
            name="status",
            field=models.BooleanField(default=0),
        ),
    ]
